{************************************************}
{                                                }
{   Turbo Vision Demo                            }
{   Copyright (c) 1990 by Borland International  }
{                                                }
{************************************************}

unit SVMCmds;

{$D-}

interface

const
  cmAbout           = 1002;
  cmPuzzle          = 1003;
  cmCalendar        = 1004;
  cmAsciiTab        = 1005;
  cmCalculator      = 1006;
  cmMouse           = 1007;
  cmColors          = 1008;
  cmSaveDesktop     = 1010;
  cmRetrieveDesktop = 1011;
  cmShowClip        = 1012;
  cmRun             = 1013;
  cmCompile         = 1014;
  cmPrimary         = 1015;
  cmClearPrimary    = 1016;
  cmExitPRG         = 1017;
  cmCompiler        = 1018;
  cmDirectories     = 1019;
  cmUserS           = 1020;
  cmFInfo           = 1022;
  cmContents        = 1023;
  cmMhm             = 1024;
  cmC_R             = 1025;
  cmMess            = 1026;
  cmWList           = 1027;
  cmDebugging       = 1028;
  cmInfoSys         = 1029;
  cmMainList        = 1030;
  cmPHelp           = 1031;

implementation

end.
