unit SVMHELP;

interface

const

  hcAbout                = 8;
  hcADD                  = 53;
  hcAND                  = 62;
  hcCalculator           = 21;
  hcCALL                 = 68;
  hcClearPF              = 17;
  hcCLf                  = 77;
  hcCMP                  = 60;
  hcCompile              = 15;
  hcComVP                = 46;
  hcCSP                  = 71;
  hcDebugger             = 4;
  hcDebuggerInfo         = 35;
  hcDEC                  = 58;
  hcDirectories          = 25;
  hcDIV                  = 56;
  hcEditCom              = 12;
  hcFind                 = 32;
  hcINC                  = 57;
  hcINCFile              = 38;
  hcInformation          = 23;
  hcInfoSysHelp          = 10;
  hcInfoSystem           = 13;
  hcInfoSystemH          = 6;
  hcJif                  = 74;
  hcJMP                  = 69;
  hcJNif                 = 75;
  hcJRNZ                 = 73;
  hcJRZ                  = 72;
  hcLogCom               = 61;
  hcMainFile             = 39;
  hcMainList             = 9;
  hcMainListH            = 7;
  hcMandS                = 45;
  hcMAPFile              = 37;
  hcMatCom               = 52;
  hcMCompile             = 14;
  hcMEdit                = 29;
  hcMessage              = 22;
  hcMFile                = 18;
  hcMHelp                = 5;
  hcMHK                  = 11;
  hcMOptions             = 24;
  hcMOV                  = 48;
  hcMovCom               = 47;
  hcMRun                 = 2;
  hcMSearch              = 31;
  hcMTools               = 19;
  hcMUL                  = 55;
  hcNEG                  = 59;
  hcNoContext            = 0;
  hcNOP                  = 79;
  hcNOT                  = 65;
  hcOR                   = 63;
  hcPOP                  = 50;
  hcPrevious             = 27;
  hcPUSH                 = 49;
  hcRegVP                = 44;
  hcReplace              = 33;
  hcRET                  = 70;
  hcRun                  = 3;
  hcSearchAgain          = 34;
  hcSetPF                = 16;
  hcShAGLogo             = 1;
  hcShowClipboard        = 30;
  hcSTf                  = 78;
  hcStreamCom            = 67;
  hcSUB                  = 54;
  hcSWPFile              = 36;
  hcTEST                 = 66;
  hcTextBlock            = 41;
  hcTextBuffer           = 40;
  hcTextCursor           = 42;
  hcUserScreen           = 20;
  hcVM                   = 43;
  hcVPCom                = 76;
  hcWindowList           = 28;
  hcWindows              = 26;
  hcXCHG                 = 51;
  hcXOR                  = 64;

implementation

end.
